apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: rollingUpdate
  template:
    metadata:
      annotations:
        co.elastic.logs/enabled: "true"
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: jithendar/payment:image_tag
          ports:
            - containerPort: 8080
          env:
            - name: CART_HOST
              value: cart
            - name: USER_HOST
              value: user
            - name: AMQP_HOST
              value: rabbitmq
            - name: AMQP_USER
              value: roboshop
            - name: AMQP_PASS
              value: roboshop123
---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
